services:
  
  nexus:
    container_name: nexus
    image: docker.io/nexusmain/nexus:2.0.0-beta.52
    user: "0" # Run as root inside the container and as current user outside the container
    volumes:
      - ./nexus:/root/.local/share/nexus
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 5000
    restart: always

  nexus-agent-python:
    container_name: nexus-agent-python
    image: docker.io/nexusmain/nexus-agent-python:2.0.0-beta.57
    user: "0" # Run as root inside the container and as current user outside the container
    volumes:
      - ./nexus-agent:/root/.local/share/nexus-agent
      - ./csv-reader-extension:/csv-reader-extension
      - ./data:/data:ro
    ports:
      - "56145:56145"
      - "8000:8000"
    restart: always